name: Snyk Vulnerability Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk_scan:
    name: Snyk Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (example for Node.js)
      - name: Install dependencies
        run: npm install

      # Step 3: Run Snyk Scan
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions@v1
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 4 (Optional): Monitor project in Snyk
      - name: Monitor project in Snyk
        uses: snyk/actions@v2
        with:
          args: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
