name: Deploy EC2 Instance with Terraform

on:
  push:
    branches:
      - master # Trigger on push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Use your preferred version

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform -chdir=terraform init

      # Step 5: Plan Terraform
      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=plan.tfplan

      # Step 6: Apply Terraform
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve plan.tfplan
